ALTER SESSION SET CURRENT_SCHEMA= THREEB;
SELECT COUNT(*) FROM DONATIONS;
SELECT COUNT(*) FROM PROJECTS;
SELECT COUNT(*) FROM GIFTCARDS;
SELECT count(*) FROM RESOURCES;
SELECT * FROM DONATIONS;

SELECT COUNT(*) FROM DONATIONS WHERE DONATIONID IS NULL;
SELECT COUNT(*) FROM DONATIONS WHERE PROJECTID IS NULL;
SELECT COUNT(*) FROM DONATIONS WHERE DONOR_ACCTID IS NULL;
SELECT COUNT(*) FROM DONATIONS WHERE CARTID IS NULL;

SELECT DONOR_CITY FROM DONATIONS GROUP BY DONOR_CITY;
SELECT DONOR_STATE FROM DONATIONS GROUP BY DONOR_STATE;
SELECT MIN(DONOR_ZIP), MAX(DONOR_ZIP) FROM DONATIONS;
SELECT MIN(DNTN_TO_PROJECT), AVG(DNTN_TO_PROJECT), MAX(DNTN_TO_PROJECT), COUNT(CASE WHEN DNTN_TO_PROJECT IS NULL THEN 1 END) FROM DONATIONS;
SELECT MIN(DNTN_OPTNL_SPRT), AVG(DNTN_OPTNL_SPRT), MAX(DNTN_OPTNL_SPRT), COUNT(CASE WHEN DNTN_OPTNL_SPRT IS NULL THEN 1 END) FROM DONATIONS;
SELECT MIN(DNTN_TOTAL), AVG(DNTN_TOTAL), MAX(DNTN_TOTAL), COUNT(CASE WHEN DNTN_TOTAL IS NULL THEN 1 END) FROM DONATIONS;

SELECT COUNT(*) FROM DONATIONS WHERE DNTN_TO_PROJECT < 0;
SELECT COUNT(*) FROM DONATIONS WHERE DNTN_OPTNL_SPRT < 0;
SELECT COUNT(*) FROM DONATIONS WHERE DNTN_TOTAL < 0;

SELECT PMT_METHOD,COUNT(*) FROM DONATIONS GROUP BY PMT_METHOD;
SELECT DNTN_DT FROM DONATIONS GROUP BY DNTN_DT;
SELECT DONOR_FULL_ZIP FROM DONATIONS GROUP BY DONOR_FULL_ZIP;

SELECT EE.* FROM PROJECTS PP
INNER JOIN ESSAYS EE
ON PP.PROJECTID = EE.PROJECTID
WHERE PP.SCHOOL_STATE = 'TX';

SELECT * FROM PROJECTS WHERE SCHOOL_STATE = 'TX';
SELECT * FROM DONATIONS;
SELECT IMPACT_LETTER FROM ESSAYS;