# DROP DATABASE IF EXISTS OPENDATA;
CREATE DATABASE OPENDATA;
USE OPENDATA;


# CREATE DATABASE
DROP TABLE DONATIONS;
DROP TABLE RESOURCES;
DROP TABLE PROJECTS;
DROP TABLE GIFTCARD;
SHOW TABLES;

CREATE TABLE PROJECTS(
	PROJECT_ID VARCHAR(255) NOT NULL,
    TEACHER_ACCID VARCHAR(255),
    SCHOOLD_ID VARCHAR(255),
    SCHOOL_NCESID VARCHAR(255),
    SCHOOL_LATITUDE DOUBLE(10, 4),
    SCHOOL_LONGITUDE DOUBLE(10, 4),
    SCHOOL_CITY VARCHAR(40),
    SCHOOL_STATE VARCHAR(40),
    SCHOOL_ZIP VARCHAR(40),
    SCHOOL_METRO VARCHAR(40),
    SCHOOL_DISTRICT VARCHAR(40),
    SCHOOL_COUNTY VARCHAR(40),
    SCHOOL_CHARTER CHAR(2),
    SCHOOL_MAGNET CHAR(2),
    SCHOOL_YEAR_ROUND CHAR(2),
    SCHOOL_NLNS CHAR(2),
    SCHOOL_KIPP CHAR(2),
    SCHOOL_CHARTER_READY_PROMISE CHAR(2),
    TEACHER_PREFIX CHAR(6),
    TEACHER_TEACH_FOR_AMERICA CHAR(2),
    TEACHER_NY_TEACHING_FELLOW CHAR(2),
    PRIMARY_FOCUS_SUBJECT VARCHAR(40),
    PRIMARY_FOCUS_AREA VARCHAR(40),
    SECONDARY_FOCUS_SUBJECT VARCHAR(40),
    SECONDARY_FOCUS_AREA VARCHAR(40),
    RESOURCE_TYPE VARCHAR(40),
    PROVERTY_LEVEL VARCHAR(40),
    GRADE_LEVEL VARCHAR(40),
    VENDOR_SHIPPING_CHARGES DECIMAL(10,2),
    SALES_TAX DECIMAL(10,2),
    PAYMENT_PROCESSING_CHARGES DECIMAL(10,2),
    FULLFIL_LABOR_MAT DECIMAL(10,2),
    TOT_PRICE_EXCL_OPT_SUP DECIMAL(10,2),
    TOT_PRICE_INCL_OPT_SUP DECIMAL(10,2),
    STUDENTS_REACHED INT,
    TOTAL_DONATIONS DECIMAL(10,2),
    NUM_DONORS INT,
    ELIG_DOB_UR_IMP_MAT CHAR(2),
    ELIG_ALM_HOME_MAT CHAR(2),
    FUNDING_STATUS VARCHAR(10),
    DATE_POSTED DATE,
    DATE_COMPLETED DATE,
    DATE_THANK_YOU_PACKET_MAILED DATE,
    DATE_EXPIRATION DATE,
    PRIMARY KEY (PROJECT_ID)    
) ENGINE=INNODB;

CREATE TABLE GIFTCARD (
	GIFTCARD_ID VARCHAR(255) NOT NULL,
    DOLLAR_TIER VARCHAR(20),
    BUYER_ACCID VARCHAR(255),
    BUYER_CITY VARCHAR(40),
    BUYER_STATE VARCHAR(40),
    BUYER_ZIP VARCHAR(40),
    DATE_PURCHASED DATE,
    BUYER_CARTID VARCHAR(255),
    RECIPIENT_ACCID VARCHAR(255),
    RECIPIENT_CITY VARCHAR(40),
    RECIPIENT_STATE VARCHAR(40),
    RECIPIENT_ZIP VARCHAR(40),
    REDEEMD CHAR(2),
    DATE_REDEEMED DATE,
    REDEEMED_CARTID VARCHAR(255),
    PAYMENT_METHOD VARCHAR(40),
    PAYMENT_INCLUDED_ACCT_CREDIT CHAR(2),
    PAYMENT_INCLUDED_CAMPAIGN_GIFT_CARD CHAR(2),
    PAYMENT_INCLUDED_WEB_PURCHASED_GIFT_CARD CHAR(2),
    PAYMENT_WAS_PROMO_MATCHED CHAR(2),
    PRIMARY KEY (GIFTCARD_ID)
);

CREATE TABLE DONATIONS (
	DONATION_ID VARCHAR(255) NOT NULL,
    PROJECT_ID VARCHAR(255) NOT NULL,
    DONOR_ACCTID VARCHAR(255),
    CART_ID VARCHAR(255),
    DONOR_CITY VARCHAR(40),
    DONOR_STATE VARCHAR(40),
    DONOR_ZIP VARCHAR(40),
    IS_TEACHER_ACCT CHAR(2),
    DONATION_TIMESTAMP DATETIME,
    DONATION_TO_PROJECT DECIMAL(8,2),
    DONATION_OPTIONAL_SUPPORT DECIMAL(8,2),
    DONATION_TOTAL DECIMAL(8,2),
    DOLLAR_AMOUNT VARCHAR(20),
    DONATION_INCLUDED_OPTIONAL_SUPPORT CHAR(2),
    PAYMENT_METHOD VARCHAR(40),
    PAYMENT_INCLUDED_ACCT_CREDIT CHAR(2),
    PAYMENT_INCLUDED_CAMPAIGN_GIFT_CARD CHAR(2),
    PAYMENT_INCLUDED_WEB_PURCHASED_GIFT_CARD CHAR(2),
    PAYMENT_WAS_PROMO_MATCHED CHAR(2),
    VIA_GIVING_PAGE CHAR(2),
    FOR_HONOREE CHAR(2),
    THANK_YOU_PACKET_MAILED CHAR(2),
    DONATION_MESSAGE VARCHAR(255),
    PRIMARY KEY (DONATION_ID)
    # FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(PROJECT_ID) ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE RESOURCES(
	RESOURCE_ID VARCHAR(255) NOT NULL,
    PROJECT_ID VARCHAR(255) NOT NULL,
    VENDOR_ID VARCHAR(255),
    VENDOR_NAME VARCHAR(255),
    ITEM_NAME VARCHAR(255),
    ITEM_NUMBER VARCHAR(40),
    ITEM_UNIT_PRICE DECIMAL(10,2),
    ITEM_QUANTITY INT,
    PRIMARY KEY (RESOURCE_ID)
    # FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(PROJECT_ID) ON DELETE CASCADE    
) ENGINE=INNODB;

# LOAD DATA
LOAD DATA LOCAL INFILE '/home/ming/Documents/BFIT data project/opendata_projects_modified.csv'
INTO TABLE PROJECTS
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SHOW WARNINGS;

LOAD DATA LOCAL INFILE '/home/ming/Documents/BFIT data project/opendata_giftcards.csv'
INTO TABLE GIFTCARD
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SHOW WARNINGS LIMIT 100;
SELECT COUNT(*) FROM GIFTCARD;

LOAD DATA LOCAL INFILE '/home/ming/Documents/BFIT data project/opendata_resources_modified_z.csv'
INTO TABLE RESOURCES
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SHOW WARNINGS LIMIT 100;

LOAD DATA LOCAL INFILE '/home/ming/Documents/BFIT data project/opendata_donations_modified.csv'
INTO TABLE DONATIONS
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SHOW WARNINGS LIMIT 100;
