SELECT PP.SCHOOL_STATE AS TO_STATE,
  DD.DONOR_STATE       AS FROM_STATE,
  SDR.ISBORDER,
  SUM(DD.DNTN_TOTAL)   AS DONATION_AMOUNT
FROM PROJECTS PP
INNER JOIN DONATIONS DD
ON PP.PROJECTID = DD.PROJECTID
INNER JOIN 
STATES_DISTANCE_RAW SDR
ON PP.SCHOOL_STATE = SDR.STATE1
AND DD.DONOR_STATE = SDR.STATE2
GROUP BY PP.SCHOOL_STATE,
  DD.DONOR_STATE,
  SDR.ISBORDER
  